 /******************************************************************************
 * Module: Port
 *
 * File Name: Port_PBcfg.c
 *
 * Description: Post Build Configuration Source file for TM4C123GH6PM Microcontroller - Port Driver
 *
 * Author: Karen Bassem
 ******************************************************************************/

#include "Port.h"

/* Module Version 1.0.0 */
#define PORT_PBCFG_SW_MAJOR_VERSION              (1U)
#define PORT_PBCFG_SW_MINOR_VERSION              (0U)
#define PORT_PBCFG_SW_PATCH_VERSION              (0U)

/* AUTOSAR Version 4.0.3 */
#define PORT_PBCFG_AR_RELEASE_MAJOR_VERSION      (4U)
#define PORT_PBCFG_AR_RELEASE_MINOR_VERSION      (0U)
#define PORT_PBCFG_AR_RELEASE_PATCH_VERSION      (3U)

/* AUTOSAR Version checking between Port_PBcfg.c and Port.h files */
#if ((PORT_PBCFG_AR_RELEASE_MAJOR_VERSION != PORT_AR_RELEASE_MAJOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_MINOR_VERSION != PORT_AR_RELEASE_MINOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_PATCH_VERSION != PORT_AR_RELEASE_PATCH_VERSION))
  #error "The AR version of PBcfg.c does not match the expected version"
#endif

/* Software Version checking between Port_PBcfg.c and Port.h files */
#if ((PORT_PBCFG_SW_MAJOR_VERSION != PORT_SW_MAJOR_VERSION)\
 ||  (PORT_PBCFG_SW_MINOR_VERSION != PORT_SW_MINOR_VERSION)\
 ||  (PORT_PBCFG_SW_PATCH_VERSION != PORT_SW_PATCH_VERSION))
  #error "The SW version of PBcfg.c does not match the expected version"
#endif
   
const Port_ConfigType Port_Configuration[] = { \
     PORTA,PIN0,PORT_PIN_IN,OFF,STD_LOW,GPIO,STD_ON,STD_ON,\
     PORTA,PIN1,PORT_PIN_IN,OFF,STD_LOW,GPIO,STD_ON,STD_ON,\
     PORTA,PIN2,PORT_PIN_OUT,OFF,STD_LOW,GPIO,STD_ON,STD_ON,\
     PORTA,PIN3,PORT_PIN_OUT,OFF,STD_HIGH,GPIO,STD_ON,STD_ON,\
     PORTA,PIN4,PORT_PIN_IN,OFF,STD_LOW,GPIO,STD_OFF,STD_ON,\
     PORTA,PIN5,PORT_PIN_IN,OFF,STD_LOW,GPIO,STD_ON,STD_OFF,\
     PORTA,PIN6,PORT_PIN_IN,OFF,STD_LOW,GPIO,STD_OFF,STD_OFF,\
     PORTA,PIN7,PORT_PIN_IN,OFF,STD_LOW,GPIO,STD_ON,STD_ON,\
       
     PORTB,PIN0,PORT_PIN_IN,OFF,STD_LOW,U1RX,STD_ON,STD_ON,\
     PORTB,PIN1,PORT_PIN_OUT,OFF,STD_LOW,U1TX,STD_ON,STD_ON,\
     PORTB,PIN2,PORT_PIN_IN,OFF,STD_LOW,GPIO,STD_ON,STD_ON,\
     PORTB,PIN3,PORT_PIN_IN,OFF,STD_LOW,GPIO,STD_ON,STD_ON,\
     PORTB,PIN4,PORT_PIN_IN,OFF,STD_LOW,GPIO,STD_ON,STD_ON,\
     PORTB,PIN5,PORT_PIN_IN,OFF,STD_LOW,GPIO,STD_ON,STD_ON,\
     PORTB,PIN6,PORT_PIN_IN,OFF,STD_LOW,GPIO,STD_ON,STD_ON,\
     PORTB,PIN7,PORT_PIN_IN,OFF,STD_LOW,GPIO,STD_ON,STD_ON,\
       
     /*PORTC,PIN0,PORT_PIN_IN,OFF,STD_LOW,GPIO,STD_ON,STD_ON,
     PORTC,PIN1,PORT_PIN_IN,OFF,STD_LOW,GPIO,STD_ON,STD_ON,\
     PORTC,PIN2,PORT_PIN_IN,OFF,STD_LOW,GPIO,STD_ON,STD_ON,\
     PORTC,PIN3,PORT_PIN_IN,OFF,STD_LOW,GPIO,STD_ON,STD_ON,*/
     PORTC,PIN4,PORT_PIN_IN,OFF,STD_LOW,GPIO,STD_ON,STD_ON,\
     PORTC,PIN5,PORT_PIN_IN,OFF,STD_LOW,GPIO,STD_ON,STD_ON,\
     PORTC,PIN6,PORT_PIN_IN,OFF,STD_LOW,GPIO,STD_ON,STD_ON,\
     PORTC,PIN7,PORT_PIN_IN,OFF,STD_LOW,GPIO,STD_ON,STD_ON,\
       
     PORTD,PIN0,PORT_PIN_IN,OFF,STD_LOW,GPIO,STD_ON,STD_ON,\
     PORTD,PIN1,PORT_PIN_IN,OFF,STD_LOW,GPIO,STD_ON,STD_ON,\
     PORTD,PIN2,PORT_PIN_IN,OFF,STD_LOW,GPIO,STD_ON,STD_ON,\
     PORTD,PIN3,PORT_PIN_IN,OFF,STD_LOW,GPIO,STD_ON,STD_ON,\
     PORTD,PIN4,PORT_PIN_IN,OFF,STD_LOW,GPIO,STD_ON,STD_ON,\
     PORTD,PIN5,PORT_PIN_IN,OFF,STD_LOW,GPIO,STD_ON,STD_ON,\
     PORTD,PIN6,PORT_PIN_IN,OFF,STD_LOW,GPIO,STD_ON,STD_ON,\
     PORTD,PIN7,PORT_PIN_IN,OFF,STD_LOW,GPIO,STD_ON,STD_ON,\
       
     PORTE,PIN0,PORT_PIN_IN,OFF,STD_LOW,GPIO,STD_ON,STD_ON,\
     PORTE,PIN1,PORT_PIN_IN,OFF,STD_LOW,GPIO,STD_ON,STD_ON,\
     PORTE,PIN2,PORT_PIN_IN,OFF,STD_LOW,GPIO,STD_ON,STD_ON,\
     PORTE,PIN3,PORT_PIN_IN,OFF,STD_LOW,GPIO,STD_ON,STD_ON,\
     PORTE,PIN4,PORT_PIN_IN,OFF,STD_LOW,GPIO,STD_ON,STD_ON,\
     PORTE,PIN5,PORT_PIN_IN,OFF,STD_LOW,GPIO,STD_ON,STD_ON,\
       
     PORTF,PIN0,PORT_PIN_IN,PULL_UP,STD_LOW,GPIO,STD_ON,STD_ON,\
     PORTF,PIN1,PORT_PIN_OUT,OFF,STD_LOW,GPIO,STD_ON,STD_ON,\
     PORTF,PIN2,PORT_PIN_OUT,OFF,STD_LOW,GPIO,STD_ON,STD_ON,\
     PORTF,PIN3,PORT_PIN_OUT,OFF,STD_LOW,GPIO,STD_ON,STD_ON,\
     PORTF,PIN4,PORT_PIN_IN,PULL_UP,STD_LOW,GPIO,STD_ON,STD_ON,\
       
   };